---

nvidia_deviceplugin_version: '1.11'

# A list of nodes in the cluster that are GPU nodes.
nvidia_gpu_nodes:
- xchem-gpu-001.novalocal

# Variable controlling the test Pod play...
# The test Pod should be able to run in any namespace
# we use 'kube-system' because we know that'll exist.
cuda_test_pod_namespace: kube-system
cuda_test_pod_timeout: 120
cuda_test_pod_min_cuda_version: '10.2'
cuda_test_pod_gpu_limit: 1

cuda_dls_deep_pod_timeout: 180
