---

# This test is based on the 'Deploy a pod that requests a GPU'
# section of the OpenShift 3.9 documentation: -
#
# https://blog.openshift.com/use-gpus-with-device-plugin-in-openshift-3-9/

# Basic pre-playbook prerequisites.
# We need the openshift/kubernetes module amongst other things...

- name: Install prerequisite Python modules
  pip:
    name:
    - openshift==0.10.0
    extra_args: --user

- name: Login (admin)
  command: oc login https://{{ okd_master_hostname }} -u {{ okd_admin }} -p {{ okd_admin_password }}
  changed_when: False

# Run the test Pod, waiting for completion.
# When it's done remove the Pod.

- name: Remove pre-existsing Vector-Add test Pod
  k8s:
    definition: "{{ lookup('template', 'cuda-vector-add-pod.yaml.j2') }}"
    state: absent
    wait: yes

# For wait conditions it's worth reading...
# https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle

- name: Create Vector-Add test Pod
  k8s:
    definition: "{{ lookup('template', 'cuda-vector-add-pod.yaml.j2') }}"

- name: Wait for Pod completion
  shell: >-
    oc get po/cuda-vector-add --namespace {{ cuda_test_pod_namespace }}
    | grep Completed
  register: result
  delay: 5
  retries: "{{ (cuda_test_pod_timeout|int / 5)|int }}"
  until: result.rc == 0
  changed_when: False

- name: Get Pod log
  command: oc logs cuda-vector-add --namespace {{ cuda_test_pod_namespace }}
  register: log_result
  changed_when: False

- name: Assert Pod success
  assert:
    that: log_result.stdout|regex_search('Test PASSED', multiline=True)
